### ISSUE TITLE
I am getting this error , do you have any ideas what it might be ? Thanks

### ISSUE THREAD

**Issue by jamenenedez** [samcorcos/apple-pay-decrypt#7]
undefined:1
P�{���#/      3��
^

SyntaxError: Unexpected token  in JSON at position 0
    at Object.parse (native)
    at PaymentToken.decrypt (/var/www/apple-pay/decrypt/node_modules/apple-pay-decrypt/index.js:26:17)
    at Object.<anonymous> (/var/www/apple-pay/decrypt/app.js:20:25)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)

**Comment by vlad1m1r** [comment]
Hi, I have the same issue, did you found the cause?

**Comment by Kandom** [comment]
This error caused by Apple Pay token data didn't encrypted by the request.csr you provided to the merchant id.
Please check your merchant id

**Comment by yassinVazquezPaz** [comment]
> undefined:1 P�{���#/ 3�� ^
> 
> SyntaxError: Unexpected token in JSON at position 0 at Object.parse (native) at PaymentToken.decrypt (/var/www/apple-pay/decrypt/node_modules/apple-pay-decrypt/index.js:26:17) at Object. (/var/www/apple-pay/decrypt/app.js:20:25) at Module._compile (module.js:577:32) at Object.Module._extensions..js (module.js:586:10) at Module.load (module.js:494:32) at tryModuleLoad (module.js:453:12) at Function.Module._load (module.js:445:3) at Module.runMain (module.js:611:10) at run (bootstrap_node.js:394:7)

I am getting a similar error. Did you solve it? Thank you!

�↨�1��������3§�q�c�↑^�lf�<�V�:� R��A����►�lj\�☼♠��/Źybf�^T�x$o/7��'-J���%z�y��⌂�♣v�m�'�A��☺�o�zZ§z$6p♠g↔�c׶B�&O���☻r����§����f�↔�No>♥���%U;@f��J��rP���H♥��R3cG����☼����"�{�/�YZs¶��"<��→C>x∟▬e6☺Ԡ���Z�ܥ�Z��Ll>�☺v;� 
�↑@8կ♀♥�Mj�<�{�`*♂8Q��☻ˠ��(�O�?�        g↓ٔ���4�5↕▲<
^

SyntaxError: Unexpected token � in JSON at position 0
